#pragma once

using namespace ATL;

template <class T>
class CProxy_IConnectEvents : public IConnectionPointImpl<T, &__uuidof( _IConnectEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
